security:
    password_hashers:
        App\Entity\Usuario: 
            algorithm: plaintext

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Usuario
                property: email # Campo usado para identificar al usuario

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            custom_authenticator: App\Security\UsuarioAuthenticator
            entry_point: App\Security\UsuarioAuthenticator
            logout:
                path: app_logout

    access_control:
    - { path: ^/login, roles: PUBLIC_ACCESS }
    - { path: ^/registro, roles: PUBLIC_ACCESS }  # Ruta de registro accesible sin autenticación
    - { path: ^/$, roles: PUBLIC_ACCESS } # Permitir acceso a la página principal
    - { path: ^/dashboard, roles: ROLE_USER } # Protege las páginas privadas
