vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /uploads/fotos_productos
            upload_destination: '%kernel.project_dir%/public/uploads/fotos_productos'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
